const langCodes = {
    _1: "Books",
    _2: "Business",
    _3: "Developer Tools",
    _4: "Education",
    _5: "Entertainment",
    _6: "Finance",
    _7: "Food & Drink",
    _8: "Games",
    _9: "Graphics & Design",
    _10: "Health & Fitness",
    _11: "Lifestyle",
    _12: "Kids",
    _13: "Magazines & Newspapers",
    _14: "Medical",
    _15: "Music",
    _16: "Navigation",
    _17: "News",
    _18: "Photo & Video",
    _19: "Productivity",
    _20: "Reference",
    _21: "Safari Extension",
    _22: "Shopping",
    _23: "Social Networking",
    _24: "Sports",
    _25: "Travel",
    _26: "Utilities",
    _27: "Weather",
}

module.exports = langCodes